services:
  myscinet:
    build: .
    command: ./start.sh
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app:Z
    working_dir: /app

  postgres:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/myscinetdb.sql:/docker-entrypoint-initdb.d/myscinetdb.sql:ro

