services:
  myscinet:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LDAP_HOSTS: ${LDAP_HOSTS}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PW: ${LDAP_BIND_PW}
      LDAP_USER_BASE: ${LDAP_USER_BASE}
      LDAP_GROUP_BASE: ${LDAP_GROUP_BASE}
      MIX_ENV: dev
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app:Z

