services:
  myscinet:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LDAP_HOSTS: ${LDAP_HOSTS}
      LDAP_PORT: ${LDAP_PORT}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_PW: ${LDAP_BIND_PW}
      LDAP_USER_BASE: ${LDAP_USER_BASE}
      LDAP_GROUP_BASE: ${LDAP_GROUP_BASE}
      LDAP_LOCAL_USER_BASE: ${LDAP_LOCAL_USER_BASE}
      LDAP_LOCAL_GROUP_BASE: ${LDAP_LOCAL_GROUP_BASE}
      MIX_ENV: dev
      REDIS_URL: ${REDIS_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "4000:4000"
    volumes:
      - ./app/.formatter.exs:/app/.formatter.exs:Z
      - ./app/.gitignore:/app/.gitignore:Z
      - ./app/assets:/app/assets:Z
      - ./app/config:/app/config:Z
      - ./app/lib:/app/lib:Z
      - ./app/mix.exs:/app/mix.exs:Z
      - ./app/mix.lock:/app/mix.lock:Z
      - ./app/priv:/app/priv:Z
      - ./app/start.sh:/app/start.sh:Z
      - ./app/test:/app/test:Z

