services:
  myscinet:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MIX_ENV: dev
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app:Z

  postgres:
    image: timescale/timescaledb-ha:pg17.5-ts2.20.3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/myscinetdb.sql:/docker-entrypoint-initdb.d/myscinetdb.sql:ro

